## config/routes.yaml
##Décription en YAML
client_prenom:
  path: /client/prenom/{prenom?}
  controller: App\Controller\ClientController::prenom
  requirements:
    prenom: '[A-Za-z0-9\-]+'

##page d'accueil site image
home:
  path: /
  controller: App\Controller\ImageController::home

##télécharger l'images
affiche:
  path: /img/data/{image}
  controller: App\Controller\ImageController::affiche

##télécharger l'images
affiches:
  path: /img/datas/{image}
  controller: App\Controller\ImageController::affiches

##menu des images
menu:
  path: /img/menu
  controller: App\Controller\ImageController::menu
##register
app_register:
  path: /register
  controller: App\Controller\RegistrationController::register
##login
app_login:
  path: /login
  controller: App\Controller\SecurityController::login
##user_show
user_show:
  path: /user/{id}
  controller: App\Controller\UserController::show
##user_edit
user_edit:
  path: /user/{id}
  controller: App\Controller\UserController::edit